version: 2

models:
  - name: fact_order_item
    description: A fact table for capturing metrics for orders at item level
    columns:
      - name: order_item_id
        description: unique identifier describing the specific item of an order
      - name: order_id
        description: unique identifier describe the order
      - name: order_date
        description: date the order was placed
      - name: customer_id
        description: unique id of the customer placing the order
      - name: quantity
        description: number of items ordered
      - name: gross_marketplace_value
        description: marketplace price of the item
